language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
env:
  - NODE_VERSION=4.4.7
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - ./mvnw clean
  - ./mvnw test
  - gulp test
  - ./mvnw package -Pprod -DskipTests
  - ./runSonarQubeAnalysis.sh
notifications:
  email: false
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
